import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
		<header className="text-center p-5 bg-blue-300">
			<Link href="/">Home</Link>
		</header>
		{children}
		<footer className="text-center p-5 bg-yellow-200">
			Footer
		</footer>
		</body>
    </html>
  );
}
